baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'My New Hugo Site'

[params]
[params.author]
name = 'John Doe'
email = 'john@doe.example.com'

[module]
[[module.imports]]
path = "github.com/mschoenlaub/hugo-atom-feeds"

[languages]
  [languages.en]
    languageName = 'English'
    title = 'In English'
    weight = 2
  [languages.de]
    languageName = 'Deutsch'
    title = 'Auf Deutsch'
    weight = 1

[taxonomies]
  author = "authors"

[outputs]
  home = ["Atom", "RSS"]
  section = ["Atom", "RSS"]
  taxonomy = ["Atom", "RSS"]
  term = ["Atom", "RSS"]
